### ISSUE TITLE
Cannot login - Cannot assign requested address

### ISSUE THREAD

**Issue by FeikoJoosten** [perforce/helix-swarm-docker#11]
Hi there,

I've followed the steps for setting up Helix Swarm using a docker container. https://www.perforce.com/manuals/swarm/Content/Swarm/docker-container.html#Run_Swarm_using_a_Docker_container

I've successfully managed to launch Swarm, and I can navigate to the login screen. However when I try to login I always get the error `Cannot assign requested address` and I have no clue what's going wrong. 

There's no errors in the logs of the docker container.

The command I'm using to start the container:
`docker run -d --name helix-swarm --network helix --network-alias helix-swarm -p 80:80 -v C:/PerforceSwarm/SwarmData/:/opt/perforce/swarm/data perforce/helix-swarm`

My config.php:
```php
<?php
    return array(
        'p4' => array(
            'port'      => 'ssl:my-amazing-domain-thats-not-this:1666',
            'user'      => 'my-amazing-admin-account-thats-not-this',
            'password'  => 'my-amazing-password-thats-not-this',
            'sso'       => 'disabled', // ['disabled'|'optional'|'enabled'] default value is 'disabled' 
         ),
         'log' => array(
             'priority'  => 3, // 7 for max, defaults to 3
         ),
         'mail' => array(
             'transport' => array(
                 'host' => 'my.mx.host',
             ),
         ),
    );
```

**Comment by daleperforce** [comment]
Helo @FeikoJoosten. I can't see from anything you have mention here that you have started the redis service as well. Take a look at the command within this section of the docs: https://www.perforce.com/manuals/swarm/Content/Swarm/docker-container.html#Setup_a_local_private_network

Swarm doesn't work without a Redis service running. You will also need to edit the .env to include the redis details. https://www.perforce.com/manuals/swarm/Content/Swarm/docker-container.html#Create_a_configuration_file

**Comment by FeikoJoosten** [comment]
Ah, didn't state that in the intial post. I'm also running redis.

My full script for starting the docker environment:
```
rem first clear old containers
docker stop helix-redis
docker rm helix-redis
docker stop helix-swarm
docker rm helix-swarm

rem then start new ones
docker run -d --name helix-redis --network helix --network-alias helix-redis -v C:/PerforceSwarm/RedisData/:/data redis redis-server --protected-mode no --port 7379 --appendonly yes

docker run -d --name helix-swarm --network helix --network-alias helix-swarm -p 80:80 -v C:/PerforceSwarm/SwarmData/:/opt/perforce/swarm/data perforce/helix-swarm
```

I've also already created the helix network using the command `docker create network helix`

The .env already has the `SWARM_REDIS` and `SWARM_REDIS_PORT` as per the example on the docs.

**Comment by FeikoJoosten** [comment]
I've also ran `docker network connect helix helix-swarm` and `docker network connect helix helix-redis` after starting the docker containers. And both the following error for both: `Error response from daemon: endpoint with name helix-swarm already exists in network helix`. So I can confirm they should already be connected to the helix network. And redis is running.

**Comment by FeikoJoosten** [comment]
Actually, looking more closely at the logs I did actually spot an error during the inital setup. (When running with the .env).

I get the exact same error as the user from this issue https://github.com/perforce/helix-swarm-docker/issues/8.

Command for setting up swarm:
`docker run -d --name helix-swarm --network helix --network-alias helix-swarm -p 80:80 -v C:/PerforceSwarm/SwarmData/:/opt/perforce/swarm/data --env-file .env perforce/helix-swarm`

redis is already running successfully before attempting to start up swarm.
And .env can be found by the command

Here is a copy of the .env
```
P4D_PORT=ssl:my-amazing-domain:1666
P4D_SUPER=my-amazing-super-account
P4D_SUPER_PASSWD=my-amazing-super-password
SWARM_USER=swarm
SWARM_PASSWD=my-amazing-password

SWARM_HOST=helix-swarm

SWARM_REDIS=helix-redis
SWARM_REDIS_PORT=7379

# If set to 'y', then extensions will be installed even if they already
# exist, overwriting existing configuration.
SWARM_FORCE_EXT=y
```

The output from configure-swarm.log
```
configure-swarm.sh: Thu Feb  1 18:38:52 UTC 2024: commencing configuration of Swarm

Summary of arguments passed:
Interactive?       [no]
Force?             [no]
P4PORT             [ssl:my-amazing-domain:1666]
Swarm user         [swarm]
Swarm password     [(present, but hidden)]
Email host         [localhost]
Create depot       [(not specified)]
Bypass Lock        [(not specified)]
Use Extensions?    [yes]
Swarm host         [helix-swarm]
Swarm port         [(default (80))]
Swarm base URL     [(default (empty))]
Create Swarm user? [yes]
Super user         [my-amazing-super-admin]
Super password     [(present, but hidden)]

Checking P4PORT [ssl:my-amazing-domain:1666]...
-establishing trust to [ssl:my-amazing-domain:1666]...
Trust already established.
Checking to see if Helix Core Server is running in Unicode mode...
-P4 command line to use: [/opt/perforce/bin/p4 -p ssl:my-amazing-domain:1666]
Attempting connection to [ssl:my-amazing-domain:1666]...
[32m-connection successful:[0m
  Server address: host.docker.internal:1666
  Server license: none
  Server version: P4D/NTX64/2023.2/2535420 (2023/12/19)
Checking Swarm user credentials...
-checking if user [swarm] exists in [ssl:my-amazing-domain:1666]...
-user does not exist
Checking super user credentials...
-checking if user [my-amazing-super-admin] exists in [ssl:my-amazing-domain:1666]...
-user exists
Obtaining Helix login ticket for [my-amazing-super-admin] in [ssl:my-amazing-domain:1666]...
[32m-login ticket obtained[0m
Checking user [my-amazing-super-admin]'s ticket against [ssl:my-amazing-domain:1666]...
Perforce password (P4PASSWD) invalid or unset.
[41m-unable to login with ticket[0m

[41mconfigure-swarm.sh: error: obtained ticket, but ticket check failed; abort[0m
```

I've also tried adding the `P4PASSWD` environment value, but to no avail. 
I can confirm the password itself it correct. I've also tried using the password generated by running `p4 login -p` and `p4 login -ap`. But that doesn't seem to help either.

**Comment by FeikoJoosten** [comment]
Well, I'm a step further. Appartently the user passed in `P4D_SUPER` needs to have the exact captilization returned by `P4 -ztag -u "$user" -P "$ticket" user -o` (taken from line 584 of `configure-swarm.sh`)

**Comment by FeikoJoosten** [comment]
Finally got it all working. Had to change the `P4D_PORT` in the .env to `ssl:host.docker.internal:1666` to make it work.
